export const SELECT_MOVIE = 'SELECT_MOVIE';
export const SAVE_REQUEST_PARAM = 'SAVE_REQUEST_PARAM';
export const SAVE_MOVIES = 'SAVE_MOVIES';
export const CHANGE_SORTING = 'CHANGE_SORTING';
export const CHANGE_FILTERING = 'CHANGE_FILTERING';
export const SAVE_SEARCH_TEXT = 'SAVE_SEARCH_TEXT';
export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';